# Generated by Django 2.1.5 on 2019-01-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modfied_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogapp.BaseModel')),
                ('email', models.EmailField(help_text='Email ID', max_length=254)),
                ('name', models.TextField(help_text='Name of the Author', max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
            bases=('blogapp.basemodel',),
        ),
    ]
