# Generated by Django 2.1.5 on 2019-01-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogapp.BaseModel')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_by', models.ForeignKey(on_delete=models.SET(1), related_name='created_categories', to='blogapp.Author')),
            ],
            options={
                'verbose_name_plural': 'Catagories',
            },
            bases=('blogapp.basemodel',),
        ),
    ]
