# Generated by Django 2.1.5 on 2019-01-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20190123_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_by',
            new_name='owner',
        ),
    ]
